services:
  web:
    image: docker.io/library/nginx
    restart: unless-stopped
    volumes:
      - frontend:/frontend:ro
      - /etc/localtime:/etc/localtime
      - ./dev/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 11221:80

volumes:
  frontend:
    driver_opts:
      o: bind
      type: none
      external: true
      device: '${PWD}/frontend'
