services:
  builder:
    image: bash:5
    volumes:
      - frontend:/frontend:rw
    command: "echo hithere >> /frontend/index.html"
  web:
    image: docker.io/library/nginx
    depends_on: builder
    restart: unless-stopped
    volumes:
      - frontend:/frontend:ro
      - /etc/localtime:/etc/localtime
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 11221:80

volumes:
  frontend:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/frontend'
