services:
  builder:
    image: bash:5
    volumes:
      - frontend:/frontend:rw
    command: "bash -c 'rm -f /frontend/index.html && echo hello > /frontend/index.html'"
  web:
    image: nginxinc/nginx-unprivileged:stable-alpine
    restart: unless-stopped
    volumes:
      - frontend:/frontend:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/localtime:/etc/localtime
    ports:
      - 11221:8080

volumes:
  frontend:
    driver_opts:
      o: bind
      type: none
      device: '${PWD}/frontend'
